--- #YAML:1.0
name:                Acme-CSV
version:             2.001
abstract:            a module providing manipulation routines for comma separated value (CSV) records
license:             lgpl
author:              
    - Christopher Rath <Christopher@Rath.ca>, Mark Mielke <Mark@Mielke.cc>, Alex Ayars <pause@nodekit.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.86
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
